// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator_BusinessLayer
{
    using System.Linq;
    using System.Collections.Generic;
    using CodeGenerator_Modules;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RuntimeTextTemplateStoredProceduresCode : RuntimeTextTemplateStoredProceduresCodeBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 5 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (!DALTemplate.IsAppendMode) { 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;\r\n" +
                    "using Microsoft.Data.SqlClient;\r\nusing System.Data;\r\nusing ");
            
            #line 11 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.ModulesLayerNameSpace));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 12 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (!DALTemplate.IsAppendMode) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 15 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.NamespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 17 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write("Repository\r\n    {\r\n");
            
            #line 19 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            
            #line 20 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.IncludeAdd) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> AddAsync(cls");
            
            #line 21 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 23 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(" != null && ");
            
            #line 23 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(@".IsFull())
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);
                    Command = new SqlCommand(""sp_");
            
            #line 31 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_Add\", Connection);\r\n\r\n                    Command.CommandType = CommandType.Stor" +
                    "edProcedure;\r\n\r\n");
            
            #line 35 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.AddOrUpdateFunctionParamertersHandled(DALTemplate.Columns)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n                    SqlParameter outputIdParam = new SqlParameter\r\n          " +
                    "          {\r\n                        ParameterName = \"@");
            
            #line 39 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOutputParameterName()));
            
            #line default
            #line hidden
            this.Write(@""",
                        SqlDbType = SqlDbType.Int,
                        Direction = ParameterDirection.Output
                    };

                    Command.Parameters.Add(outputIdParam);

                    await Connection.OpenAsync();
                    await Command.ExecuteNonQueryAsync();

                    if (outputIdParam.Value != null)
                    {
                        ");
            
            #line 51 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 51 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOutputParameterName()));
            
            #line default
            #line hidden
            this.Write(@" = (int)outputIdParam.Value;
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                catch (SqlException ex)
                {
                    clsEventLog.WriteToEventLog($""Error occurred while adding ");
            
            #line 61 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(": {ex.Message}\", enLogType.Error);\r\n                }\r\n                catch (Exc" +
                    "eption ex)\r\n                {\r\n                    clsEventLog.WriteToEventLog($" +
                    "\"Error occurred while adding ");
            
            #line 65 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(@": {ex.Message}"", enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 84 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 86 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.IncludeUpdate) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> UpdateAsync(cls");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 89 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
if (DALTemplate.Columns.Find(x => x.Name == DALTemplate.UpdateParameterName).Type == "string") { 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(" != null && !string.IsNullOrWhiteSpace(");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.UpdateParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(") && ");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(".IsFull())\r\n");
            
            #line 91 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            
            #line 92 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.Columns.Find(x => x.Name == DALTemplate.UpdateParameterName).Type != "string") { 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 93 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(" != null && ");
            
            #line 93 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 93 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleCorrectCheckParamerter(DALTemplate.UpdateParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(" && ");
            
            #line 93 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(".IsFull())\r\n");
            
            #line 94 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);

                    Command = new SqlCommand(""sp_");
            
            #line 103 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_Update\", Connection);\r\n\r\n                    Command.CommandType = CommandType.S" +
                    "toredProcedure;\r\n\r\n");
            
            #line 107 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.AddOrUpdateFunctionParamertersHandled(DALTemplate.Columns)));
            
            #line default
            #line hidden
            this.Write(@"

                    await Connection.OpenAsync();

                    return await Command.ExecuteNonQueryAsync() > 0;
                }
                catch (SqlException ex)
                {
                    clsEventLog.WriteToEventLog($""Error occurred while updating ");
            
            #line 115 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(": {ex.Message}\", enLogType.Error);\r\n                }\r\n                catch (Exc" +
                    "eption ex)\r\n                {\r\n                    clsEventLog.WriteToEventLog($" +
                    "\"Error occurred while updating ");
            
            #line 119 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(@": {ex.Message}"", enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 138 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 140 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.IncludeFind) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<cls");
            
            #line 141 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write("?> FindAsync(");
            
            #line 141 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleParameter(DALTemplate.FindParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 143 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleCorrectCheckParamerter(DALTemplate.FindParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@")
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;
                SqlDataReader? Reader = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);
                    Command = new SqlCommand(""sp_");
            
            #line 152 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_FindBy_");
            
            #line 152 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", Connection);\r\n\r\n                    Command.CommandType = CommandType.StoredPr" +
                    "ocedure;\r\n\r\n                    Command.Parameters.AddWithValue(\"@");
            
            #line 156 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 156 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n                    await Connection.OpenAsync();\r\n\r\n                    Re" +
                    "ader = await Command.ExecuteReaderAsync();\r\n\r\n                    if (await Read" +
                    "er.ReadAsync())\r\n                    {\r\n                        return new cls");
            
            #line 164 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write("\r\n                        {\r\n");
            
            #line 166 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.FindOrGetAllFunctionParamertersHandled(DALTemplate.Columns)));
            
            #line default
            #line hidden
            this.Write("\r\n                        };\r\n                    }\r\n                }\r\n         " +
                    "       catch (SqlException ex)\r\n                {\r\n                    clsEventL" +
                    "og.WriteToEventLog($\"Error occurred while fetching ");
            
            #line 172 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(": {ex.Message}\", enLogType.Error);\r\n                }\r\n                catch (Exc" +
                    "eption ex)\r\n                {\r\n                    clsEventLog.WriteToEventLog($" +
                    "\"Error occurred while fetching ");
            
            #line 176 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(@": {ex.Message}"", enLogType.Error);
                }
                finally
                {
                    if (Reader != null)
                    {
                        Reader.Close();
                        Reader.Dispose();
                    }

                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return  null;
        }
");
            
            #line 201 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 203 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.IncludeGetAll) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<List<cls");
            
            #line 204 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(">?> GetAll");
            
            #line 204 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("Async()\r\n        {\r\n            SqlConnection? Connection = null;\r\n            Sq" +
                    "lCommand? Command = null;\r\n            SqlDataReader? Reader = null;\r\n\r\n        " +
                    "    List<cls");
            
            #line 210 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(">? ListOf");
            
            #line 210 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n\r\n            try\r\n            {\r\n                Connection = new SqlC" +
                    "onnection(clsConnectionString.ConnectionString);\r\n                Command = new " +
                    "SqlCommand(\"sp_");
            
            #line 215 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(@"_GetAll"", Connection);

                Command.CommandType = CommandType.StoredProcedure;

                await Connection.OpenAsync();

                Reader = await Command.ExecuteReaderAsync();

                if (Reader.HasRows)
                {
                    ListOf");
            
            #line 225 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(" = new List<cls");
            
            #line 225 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n                    while (await Reader.ReadAsync())\r\n                   " +
                    " {\r\n                        ListOf");
            
            #line 229 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(".Add(new cls");
            
            #line 229 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write("\r\n                        {\r\n");
            
            #line 231 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.FindOrGetAllFunctionParamertersHandled(DALTemplate.Columns)));
            
            #line default
            #line hidden
            this.Write("\r\n                        });\r\n                    }\r\n                }\r\n        " +
                    "    }\r\n            catch (SqlException ex)\r\n            {\r\n                clsEv" +
                    "entLog.WriteToEventLog($\"Error occurred while fetching all ");
            
            #line 238 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(": {ex.Message}\", enLogType.Error);\r\n            }\r\n            catch (Exception e" +
                    "x)\r\n            {\r\n                clsEventLog.WriteToEventLog($\"Error occurred " +
                    "while fetching all ");
            
            #line 242 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(@": {ex.Message}"", enLogType.Error);
            }
            finally
            {
                if (Reader != null)
                {
                    Reader.Close();
                    Reader.Dispose();
                }

                if (Command != null)
                {
                    Command.Dispose();
                }

                if (Connection != null)
                {
                    Connection.Close();
                    Connection.Dispose();
                }
            }

            return ListOf");
            
            #line 264 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n");
            
            #line 266 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 268 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.IncludeDelete) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> DeleteAsync(");
            
            #line 269 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleParameter(DALTemplate.DeleteParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 271 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleCorrectCheckParamerter(DALTemplate.DeleteParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@")
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);
                    Command = new SqlCommand(""sp_");
            
            #line 279 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_Delete\", Connection);\r\n\r\n                    Command.CommandType = CommandType.S" +
                    "toredProcedure;\r\n\r\n                    Command.Parameters.AddWithValue(\"@");
            
            #line 283 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 283 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@");

                    await Connection.OpenAsync();

                    return await Command.ExecuteNonQueryAsync() > 0;
                }
                catch (SqlException ex)
                {
                    clsEventLog.WriteToEventLog($""Error occurred while deleting ");
            
            #line 291 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(": {ex.Message}\", enLogType.Error);\r\n                }\r\n                catch (Exc" +
                    "eption ex)\r\n                {\r\n                    clsEventLog.WriteToEventLog($" +
                    "\"Error occurred while deleting ");
            
            #line 295 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(@": {ex.Message}"", enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 314 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 316 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (DALTemplate.IncludeExist) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> IsExistAsync(");
            
            #line 317 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleParameter(DALTemplate.ExistParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 319 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.HandleCorrectCheckParamerter(DALTemplate.ExistParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@")
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);
                    Command = new SqlCommand(""sp_");
            
            #line 327 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_IsExist\", Connection);\r\n\r\n                    Command.CommandType = CommandType." +
                    "StoredProcedure;\r\n\r\n                    Command.Parameters.AddWithValue(\"@");
            
            #line 331 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 331 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@");

                    SqlParameter isFoundParam = new SqlParameter
                    {
                        ParameterName = ""@IsFound"",
                        SqlDbType = SqlDbType.Bit,
                        Direction = ParameterDirection.Output
                    };

                    Command.Parameters.Add(isFoundParam);
                    
                    await Connection.OpenAsync();
                    await Command.ExecuteNonQueryAsync();

                    return isFoundParam.Value == null ? false : (bool)isFoundParam.Value;
                }
                catch (SqlException ex)
                {
                    clsEventLog.WriteToEventLog($""Error occurred while checking ");
            
            #line 349 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(" existence: {ex.Message}\", enLogType.Error);\r\n                }\r\n                " +
                    "catch (Exception ex)\r\n                {\r\n                    clsEventLog.WriteTo" +
                    "EventLog($\"Error occurred while checking ");
            
            #line 353 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALTemplate.TableSingleName));
            
            #line default
            #line hidden
            this.Write(@" existence: {ex.Message}"", enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 372 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        // Never delete this comment\r\n        // [EXTRA_METHODS_HERE]\r\n\r\n");
            
            #line 377 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 if (!DALTemplate.IsAppendMode) { 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            
            #line 380 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 384 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresCode.tt"


public RuntimeTextTemplateDataAccessLayer DALTemplate = new RuntimeTextTemplateDataAccessLayer();

public string GetOutputParameterName()
{
    clsColumnDataDataAccessLayer Col = DALTemplate.Columns.Find(x => x.IsPrimaryKey);

    if (Col != null)
    {
        return Col.NameWithout_;
    }

    return DALTemplate.Columns[0].NameWithout_;
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RuntimeTextTemplateStoredProceduresCodeBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
