// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator_BusinessLayer
{
    using System.Linq;
    using CodeGenerator_Modules;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RuntimeTextTemplateUiLayerLogic : RuntimeTextTemplateUiLayerLogicBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Windows.Forms;\r\nusing System.ComponentModel;\r\nusing System;\r\nusing S" +
                    "ystem.Collections.Generic;\r\nusing System.Threading.Tasks;\r\nusing ModulesLayer;\r\n" +
                    "\r\n\r\nnamespace ");
            
            #line 13 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 15 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "fm" : "uctrl"));
            
            #line default
            #line hidden
            
            #line 15 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 15 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "Form" : "UserControl"));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public  ");
            
            #line 17 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "fm" : "uctrl"));
            
            #line default
            #line hidden
            
            #line 17 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            InitializeComponent();\r\n        }\r\n\r\n");
            
            #line 22 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 if (IsInput && IsForm) { 
            
            #line default
            #line hidden
            this.Write(" \r\n        void btCancel_Click(object sender, EventArgs e)\r\n        {\r\n          " +
                    "  this.Close();\r\n        }\r\n");
            
            #line 27 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 29 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write(@"        void ShowMissingMessage()
        {
            MessageBox.Show(""One of the requirements is missing"", ""Error"", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }

        void btSave_Click(object sender, EventArgs e)
        {
            if (!this.ValidateChildren())
            {
                ShowMissingMessage();
                return;
            }

            if (
");
            
            #line 44 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 for (short i = 0; i < ListInputOfControlsNotAllowNull.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 45 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListInputOfControlsNotAllowNull[i]));
            
            #line default
            #line hidden
            
            #line 45 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < ListInputOfControlsNotAllowNull.Count - 1) ? " &&" : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 46 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 } 
            
            #line default
            #line hidden
            this.Write("               )\r\n            {\r\n                \r\n            }\r\n            els" +
                    "e\r\n            {\r\n                ShowMissingMessage();\r\n            }\r\n        " +
                    "}\r\n\r\n");
            
            #line 57 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 if (ListInputOfControlsNotAllowNull.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("        void InputControls_ValidatingHelper(MaskedTextBox? maskedtextBox, CancelE" +
                    "ventArgs e)\r\n        {\r\n            if (maskedtextBox != null)\r\n            {\r\n " +
                    "               if (string.IsNullOrWhiteSpace(maskedtextBox.Text))\r\n             " +
                    "   {\r\n                    errorProvider1.SetError(maskedtextBox, \"This box shoul" +
                    "d not be empty!\");\r\n                    e.Cancel = true;\r\n                }\r\n   " +
                    "             else if (!maskedtextBox.MaskCompleted)\r\n                {\r\n        " +
                    "            errorProvider1.SetError(maskedtextBox, \"The requirements for this bo" +
                    "x are not complete!\");\r\n                    e.Cancel = true;\r\n                }\r" +
                    "\n                else\r\n                {\r\n                    errorProvider1.Set" +
                    "Error(maskedtextBox, \"\");\r\n                    e.Cancel = false;\r\n              " +
                    "  }\r\n            }\r\n        }\r\n\r\n        void InputControls_ValidatingHelper(Tex" +
                    "tBox? textBox, CancelEventArgs e)\r\n        {\r\n            if (textBox != null)\r\n" +
                    "            {\r\n                if (string.IsNullOrWhiteSpace(textBox.Text))\r\n   " +
                    "             {\r\n                    errorProvider1.SetError(textBox, \"This box s" +
                    "hould not be empty!\");\r\n                    e.Cancel = true;\r\n                }\r" +
                    "\n                else\r\n                {\r\n                    errorProvider1.Set" +
                    "Error(textBox, \"\");\r\n                    e.Cancel = false;\r\n                }\r\n " +
                    "           }\r\n        }\r\n\r\n        void InputControls_ValidatingHelper(ComboBox?" +
                    " comboBox, CancelEventArgs e)\r\n        {\r\n            if (comboBox != null)\r\n   " +
                    "         {\r\n                if (string.IsNullOrWhiteSpace(comboBox.Text))\r\n     " +
                    "           {\r\n                    errorProvider1.SetError(comboBox, \"This box sh" +
                    "ould not be empty!\");\r\n                    e.Cancel = true;\r\n                }\r\n" +
                    "                else\r\n                {\r\n                    errorProvider1.SetE" +
                    "rror(comboBox, \"\");\r\n                    e.Cancel = false;\r\n                }\r\n " +
                    "           }\r\n        }\r\n\r\n        void InputControls_Validating(object sender, " +
                    "CancelEventArgs e)\r\n        {\r\n            if (sender is TextBox)\r\n            {" +
                    "\r\n                TextBox? textBox = sender as TextBox;\r\n\r\n                Input" +
                    "Controls_ValidatingHelper(textBox, e);\r\n            }\r\n            else if (send" +
                    "er is MaskedTextBox)\r\n            {\r\n                MaskedTextBox? maskedtextBo" +
                    "x = sender as MaskedTextBox;\r\n\r\n                InputControls_ValidatingHelper(m" +
                    "askedtextBox, e);\r\n            }\r\n            else if (sender is ComboBox)\r\n    " +
                    "        {\r\n                ComboBox? comboBox = sender as ComboBox;\r\n\r\n         " +
                    "       InputControls_ValidatingHelper(comboBox, e);\r\n            }\r\n        }\r\n");
            
            #line 135 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 } 
            
            #line default
            #line hidden
            
            #line 136 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 } 
            
            #line default
            #line hidden
            
            #line 137 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("        void FillDataGirdView(List<cls");
            
            #line 138 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("> ListOf");
            
            #line 138 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (ListOf");
            
            #line 140 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Count > 0)\r\n            {\r\n                lbNumberOfRowsResult.Text = ListOf");
            
            #line 142 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Count.ToString();\r\n\r\n                dgv");
            
            #line 144 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Rows.Clear();\r\n\r\n                for (int i = 0; i < ListOf");
            
            #line 146 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Count; i++)\r\n                {\r\n                    dgv");
            
            #line 148 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Rows.Add(new object[] {\r\n");
            
            #line 149 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 for (short i = 0; i < ListOfColunmData.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("                     ListOf");
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("[i].");
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i == ListOfColunmData.Count - 1) ? "" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 151 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                         });\r\n                }\r\n            }\r\n        }\r\n\r\n    " +
                    "    void FillComboBox()\r\n        {\r\n            //cbFilter.Items.Add(\"All\");\r\n\r\n" +
                    "\r\n            //cbFilter.SelectedIndex = 0;\r\n        }\r\n\r\n        void fm");
            
            #line 165 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("_Load(object sender, EventArgs e)\r\n        {\r\n            //FillDataGirdView(");
            
            #line 167 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("Service.GetAll");
            
            #line 167 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(@"());

            //FillComboBox();
        }

        void cbFilter_SelectedIndexChanged(object sender, EventArgs e)
        {
            mtxtbFilterValue.Clear();
        }

        void btFind_Click(object sender, EventArgs e)
        {
            

            mtxtbFilterValue.Focus();
        }
");
            
            #line 183 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n    }\r\n}\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 191 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerLogic.tt"



List <string> GetListInputOfControlsNotAllowNull()
{
    List<string> ListInputOfControlsNotAllowNull = new List<string>();

    enControls ControlName = enControls.None;

    for (short i = 0; i < ListOfColunmData.Count; i++)
    {
        Enum.TryParse(ListOfColunmData[i].ControlName, out ControlName);

        if (ListOfColunmData[i].Generate && !ListOfColunmData[i].IsNullable && (ControlName == enControls.TextBox || ControlName == enControls.MaskedTextBox || ControlName == enControls.ComboBox))
        {
            ListInputOfControlsNotAllowNull.Add($"!string.IsNullOrWhiteSpace({RuntimeTextTemplateUiLayerDesigner.GetControlName(ControlName, ListOfColunmData[i].NameWithout_)}.Text)");
        }
    }

    return ListInputOfControlsNotAllowNull;
}

public string NameSpace { get; set; } = "";

string _TableSingleName = "";
public string TableSingleName
{
    get
    {
        return _TableSingleName;
    }
    set
    {
        _TableSingleName = value;

        _TableSingleName = _TableSingleName?.Replace("_", "");
    }
}

string _TableName = "";
public string TableName
{
    get 
    {    
        return _TableName;
    }
    set
    {
        _TableName = value;

        _TableName = _TableName?.Replace("_", "");
    }
}

public bool IsInput { get; set; }
public bool IsView { get; set; }

// لو هذا المتغير بيساوي false معناها ان هيتم انشاء user control
public bool IsForm { get; set; }

private List<string> ListInputOfControlsNotAllowNull = new List<string>();

private List<clsColumnDataUILayer> _ListOfColunmData {  get; set; }
public List<clsColumnDataUILayer> ListOfColunmData 
{
     get
     {
          if (_ListOfColunmData == null)
          {
               return new List<clsColumnDataUILayer>();
          }
          else
          {
               return _ListOfColunmData;
          }
     }
     set
     {
          _ListOfColunmData = value;

          if (_ListOfColunmData != null)
          {
                ListInputOfControlsNotAllowNull = GetListInputOfControlsNotAllowNull();
          }
     }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RuntimeTextTemplateUiLayerLogicBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
