// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator_BusinessLayer
{
    using System.Linq;
    using System.Collections.Generic;
    using CodeGenerator_Modules;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RuntimeTextTemplateStoredProceduresScript : RuntimeTextTemplateStoredProceduresScriptBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nUSE ");
            
            #line 6 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write("\r\nGO\r\n\r\n\r\n");
            
            #line 10 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 if (SPTemplate.DALTemplate.IncludeAdd) { 
            
            #line default
            #line hidden
            this.Write("CREATE PROCEDURE sp_");
            
            #line 11 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_Add\r\n    ");
            
            #line 12 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SP_AddArUpdateFunctionHandled(true)));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n    \r\n    BEGIN TRY\r\n        BEGIN TRANSACTION;" +
                    "\r\n\r\n        INSERT INTO [");
            
            #line 20 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("] (\r\n");
            
            #line 21 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 for (short i = 0; i < SPTemplate.DALTemplate.Columns.Count; i++) { 
                                if (SPTemplate.DALTemplate.Columns[i].IsPrimaryKey)
                                            continue;
            
            #line default
            #line hidden
            this.Write("        [");
            
            #line 24 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns[i].Name));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 24 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < SPTemplate.DALTemplate.Columns.Count - 1) ? ", " : " )"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 25 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        VALUES (\r\n");
            
            #line 27 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 for (short i = 0; i < SPTemplate.DALTemplate.Columns.Count; i++) { 
                                    if (SPTemplate.DALTemplate.Columns[i].IsPrimaryKey)
                                            continue;
            
            #line default
            #line hidden
            this.Write("        @");
            
            #line 30 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns[i].NameWithout_));
            
            #line default
            #line hidden
            
            #line 30 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < SPTemplate.DALTemplate.Columns.Count - 1) ? ", " : " );"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        SET @");
            
            #line 33 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.GetOutputParameterName()));
            
            #line default
            #line hidden
            this.Write(@" = SCOPE_IDENTITY();

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END;
GO
");
            
            #line 49 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-- ============================================================================" +
                    "==========\r\n\r\n");
            
            #line 53 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 if (SPTemplate.DALTemplate.IncludeUpdate) { 
            
            #line default
            #line hidden
            this.Write("    CREATE PROCEDURE sp_");
            
            #line 54 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_Update\r\n    ");
            
            #line 55 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SP_AddArUpdateFunctionHandled(false)));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    BEGIN TRY\r\n        BEGIN TRANSACTION;\r\n\r\n        UPDATE [");
            
            #line 61 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("] SET \r\n");
            
            #line 62 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 for (short i = 0; i < SPTemplate.DALTemplate.Columns.Count; i++) { 
                                if (SPTemplate.DALTemplate.Columns[i].IsPrimaryKey)
                                            continue;
            
            #line default
            #line hidden
            this.Write("        [");
            
            #line 65 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns[i].Name));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 65 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns[i].NameWithout_));
            
            #line default
            #line hidden
            
            #line 65 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < SPTemplate.DALTemplate.Columns.Count - 1) ? ", " : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 66 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        WHERE [");
            
            #line 67 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.UpdateParameterName));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 67 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.UpdateParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@";

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END;
GO
");
            
            #line 83 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-- ============================================================================" +
                    "==========\r\n\r\n");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 if (SPTemplate.DALTemplate.IncludeFind) { 
            
            #line default
            #line hidden
            this.Write("    CREATE PROCEDURE sp_");
            
            #line 88 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_FindBy_");
            
            #line 88 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\r\n    @");
            
            #line 89 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 89 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns.Find(x => x.Name == SPTemplate.DALTemplate.FindParameterName)?.Type.ToUpper()));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    SELECT * FROM ");
            
            #line 94 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 94 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.FindParameterName));
            
            #line default
            #line hidden
            this.Write(" = @");
            
            #line 94 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(";\r\nEND;\r\nGO\r\n");
            
            #line 97 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-- ============================================================================" +
                    "==========\r\n\r\n");
            
            #line 101 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 if (SPTemplate.DALTemplate.IncludeGetAll) { 
            
            #line default
            #line hidden
            this.Write("    CREATE PROCEDURE sp_");
            
            #line 102 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_GetAll\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    SELECT * FROM ");
            
            #line 107 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\nEND;\r\nGO\r\n");
            
            #line 110 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-- ============================================================================" +
                    "==========\r\n\r\n");
            
            #line 114 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 if (SPTemplate.DALTemplate.IncludeDelete) { 
            
            #line default
            #line hidden
            this.Write("    CREATE PROCEDURE sp_");
            
            #line 115 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_Delete\r\n    @");
            
            #line 116 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 116 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns.Find(x => x.Name == SPTemplate.DALTemplate.DeleteParameterName)?.Type.ToUpper()));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    BEGIN TRY\r\n        BEGIN TRANSACTION;\r\n\r\n        DELETE FROM ");
            
            #line 122 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 122 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.DeleteParameterName));
            
            #line default
            #line hidden
            this.Write(" = @");
            
            #line 122 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@";

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END;
GO
");
            
            #line 138 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-- ============================================================================" +
                    "==========\r\n\r\n");
            
            #line 142 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 if (SPTemplate.DALTemplate.IncludeExist) { 
            
            #line default
            #line hidden
            this.Write("    CREATE PROCEDURE sp_");
            
            #line 143 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write("_IsExist\r\n    @");
            
            #line 144 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 144 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.Columns.Find(x => x.Name == SPTemplate.DALTemplate.ExistParameterName)?.Type.ToUpper()));
            
            #line default
            #line hidden
            this.Write(",\r\n    @IsFound BIT OUTPUT\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    IF EXISTS (SELE" +
                    "CT 1 FROM ");
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.TableName));
            
            #line default
            #line hidden
            this.Write(" WHERE ");
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.ExistParameterName));
            
            #line default
            #line hidden
            this.Write(" = @");
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SPTemplate.DALTemplate.ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        SET @IsFound = 1;\r\n    ELSE\r\n        SET @IsFound = 0;\r\nEND;\r\nGO\r\n");
            
            #line 156 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-- ============================================================================" +
                    "==========\r\n\r\n\r\n-- Never delete this comment\r\n-- [EXTRA_CODE_HERE]\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 166 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateStoredProceduresScript.tt"


public string DatabaseName { get; set;} = "";

public RuntimeTextTemplateStoredProceduresCode SPTemplate = new RuntimeTextTemplateStoredProceduresCode();

private string SP_AddArUpdateFunctionHandled(bool IsAddFunction)
{
    string Value = "";

    for (short i = 0; i < SPTemplate.DALTemplate.Columns.Count; i++)
    {
        if (IsAddFunction && SPTemplate.DALTemplate.Columns[i].IsPrimaryKey)
        {
            Value += $"@{SPTemplate.DALTemplate.Columns[i].NameWithout_}  {SPTemplate.DALTemplate.Columns[i].Type.ToUpper()} OUTPUT{GetCorrectEnd(i, SPTemplate.DALTemplate.Columns.Count, SPTemplate.DALTemplate.Columns[i].IsNullable)}";
        }
        else if (SPTemplate.DALTemplate.Columns[i].Type == "varchar" || SPTemplate.DALTemplate.Columns[i].Type == "nvarchar")
        {
            Value += $"@{SPTemplate.DALTemplate.Columns[i].NameWithout_}  {SPTemplate.DALTemplate.Columns[i].Type.ToUpper()}(100){GetCorrectEnd(i, SPTemplate.DALTemplate.Columns.Count, SPTemplate.DALTemplate.Columns[i].IsNullable)}";
        }
        else if (SPTemplate.DALTemplate.Columns[i].Type == "char" || SPTemplate.DALTemplate.Columns[i].Type == "nchar")
        {
            Value += $"@{SPTemplate.DALTemplate.Columns[i].NameWithout_}  {SPTemplate.DALTemplate.Columns[i].Type.ToUpper()}(10){GetCorrectEnd(i, SPTemplate.DALTemplate.Columns.Count, SPTemplate.DALTemplate.Columns[i].IsNullable)}";
        }
        else
        {
            Value += $"@{SPTemplate.DALTemplate.Columns[i].NameWithout_}  {SPTemplate.DALTemplate.Columns[i].Type.ToUpper()}{GetCorrectEnd(i, SPTemplate.DALTemplate.Columns.Count, SPTemplate.DALTemplate.Columns[i].IsNullable)}";
        }
    }

    return Value;
}

private string GetCorrectEnd(short i, int Count, bool IsNullable)
{
    string Value = $"{GetCorrectEnd(IsNullable)}";
    Value += i + 1 == Count ? "\n\t" : ",\n\t";

    return Value;
}

private string GetCorrectEnd(bool IsNullable)
{
    return IsNullable ? " = NULL" : "";
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RuntimeTextTemplateStoredProceduresScriptBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
