// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator_BusinessLayer
{
    using System.Linq;
    using CodeGenerator_Modules;
    using System.Collections.Generic;
    using System.Drawing;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RuntimeTextTemplateUiLayerDesigner : RuntimeTextTemplateUiLayerDesignerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nnamespace ");
            
            #line 7 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    partial class ");
            
            #line 9 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "fm" : "uctrl"));
            
            #line default
            #line hidden
            
            #line 9 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@" 
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name=""disposing"">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
");
            
            #line 37 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write(@"            this.lbNumberOfRowsResult = new System.Windows.Forms.Label();
            this.cbFilter = new System.Windows.Forms.ComboBox();
            this.btFind = new System.Windows.Forms.Button();
            this.lbFilterBy = new System.Windows.Forms.Label();
            this.mtxtbFilterValue = new System.Windows.Forms.MaskedTextBox();
            this.dgv");
            
            #line 43 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" = new System.Windows.Forms.DataGridView();\r\n");
            
            #line 44 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfColunmData.Count; i++) { 
            
            #line default
            #line hidden
            
            #line 45 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (ListOfColunmData[i].Type == "bit") { 
            
            #line default
            #line hidden
            this.Write("            this.col");
            
            #line 46 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(" = new System.Windows.Forms.DataGridViewCheckBoxColumn();\r\n");
            
            #line 47 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 48 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (ListOfColunmData[i].Type != "bit") { 
            
            #line default
            #line hidden
            this.Write("            this.col");
            
            #line 49 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(" = new System.Windows.Forms.DataGridViewTextBoxColumn();\r\n");
            
            #line 50 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 51 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 52 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 53 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("            this.components = new System.ComponentModel.Container();\r\n");
            
            #line 55 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 56 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfInitializedControls.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 57 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfInitializedControls[i]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 58 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 59 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("            this.btSave = new System.Windows.Forms.Button();\r\n");
            
            #line 61 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 61 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput && IsForm) { 
            
            #line default
            #line hidden
            this.Write("            this.btCancel = new System.Windows.Forms.Button();\r\n");
            
            #line 63 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 63 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.com" +
                    "ponents);\r\n            ((System.ComponentModel.ISupportInitialize)(this.errorPro" +
                    "vider1)).BeginInit();\r\n");
            
            #line 66 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 67 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("            ((System.ComponentModel.ISupportInitialize)(this.dgv");
            
            #line 68 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(")).BeginInit();\r\n");
            
            #line 69 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.SuspendLayout();\r\n");
            
            #line 71 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfInitializedProperties.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 72 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfInitializedProperties[i]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 73 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 74 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write(@"            // 
            // btSave
            // 
            this.btSave.BackColor = System.Drawing.Color.Silver;
            this.btSave.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.btSave.FlatAppearance.BorderSize = 2;
            this.btSave.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Silver;
            this.btSave.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gray;
            this.btSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btSave.Font = new System.Drawing.Font(""Microsoft Sans Serif"", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            ");
            
            #line 85 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "this.btSave.Location = new System.Drawing.Point(909, 456);" : "this.btSave.Location = new System.Drawing.Point(929, 504);"));
            
            #line default
            #line hidden
            this.Write(@"
            this.btSave.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btSave.Name = ""btSave"";
            this.btSave.Size = new System.Drawing.Size(120, 40);
            this.btSave.TabIndex = 6;
            this.btSave.Text = ""Save"";
            this.btSave.UseVisualStyleBackColor = false;
            this.btSave.Click += new System.EventHandler(this.btSave_Click);
");
            
            #line 93 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 93 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput && IsForm) { 
            
            #line default
            #line hidden
            this.Write(@"            // 
            // btCancel
            // 
            this.btCancel.BackColor = System.Drawing.Color.Silver;
            this.btCancel.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.btCancel.FlatAppearance.BorderSize = 2;
            this.btCancel.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Silver;
            this.btCancel.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gray;
            this.btCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btCancel.Font = new System.Drawing.Font(""Microsoft Sans Serif"", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCancel.Location = new System.Drawing.Point(786, 456);
            this.btCancel.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btCancel.Name = ""btCancel"";
            this.btCancel.Size = new System.Drawing.Size(120, 40);
            this.btCancel.TabIndex = 20;
            this.btCancel.Text = ""Cancel"";
            this.btCancel.UseVisualStyleBackColor = false;
            this.btCancel.Click += new System.EventHandler(this.btCancel_Click);
");
            
            #line 112 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 112 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("            // \r\n            // errorProvider1\r\n            // \r\n            this" +
                    ".errorProvider1.ContainerControl = this;\r\n");
            
            #line 117 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 118 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("            // \r\n            // dgv");
            
            #line 120 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n            // \r\n            this.dgv");
            
            #line 122 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".AllowUserToAddRows = false;\r\n            this.dgv");
            
            #line 123 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".AllowUserToDeleteRows = false;\r\n            this.dgv");
            
            #line 124 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".AllowUserToResizeRows = false;\r\n            this.dgv");
            
            #line 125 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".AllowUserToOrderColumns = true;\r\n            this.dgv");
            
            #line 126 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeig" +
                    "htSizeMode.AutoSize;\r\n            this.dgv");
            
            #line 127 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {\r\n");
            
            #line 128 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfColunmData.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("            this.col");
            
            #line 129 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            
            #line 129 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i == ListOfColunmData.Count - 1) ? "});" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 130 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.dgv");
            
            #line 131 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Dock = System.Windows.Forms.DockStyle.None;\r\n            this.dgv");
            
            #line 132 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Location = new System.Drawing.Point(0, 222);\r\n            this.dgv");
            
            #line 133 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".MultiSelect = false;\r\n            this.dgv");
            
            #line 134 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Name = \"dgv");
            
            #line 134 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\";\r\n            this.dgv");
            
            #line 135 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".RowHeadersVisible = false;\r\n            this.dgv");
            
            #line 136 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".RowHeadersWidth = 51;\r\n            this.dgv");
            
            #line 137 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".RowTemplate.Height = 24;\r\n            this.dgv");
            
            #line 138 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;\r\n " +
                    "           this.dgv");
            
            #line 139 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Size = new System.Drawing.Size ");
            
            #line 139 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "(1030, 250)" : "(1050, 250)"));
            
            #line default
            #line hidden
            this.Write(";\r\n            this.dgv");
            
            #line 140 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".TabIndex = 10;\r\n");
            
            #line 141 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfColunmData.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("            // \r\n            // col");
            
            #line 143 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write("\r\n            // \r\n            this.col");
            
            #line 145 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(".HeaderText = \"");
            
            #line 145 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].Name.Replace("_", " ")));
            
            #line default
            #line hidden
            this.Write("\";\r\n            this.col");
            
            #line 146 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(".MinimumWidth = 6;\r\n            this.col");
            
            #line 147 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(".Name = \"col");
            
            #line 147 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write("\";\r\n            this.col");
            
            #line 148 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(".ReadOnly = true;\r\n            this.col");
            
            #line 149 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(".Width = 150;\r\n");
            
            #line 150 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            // \r\n            // lbNumberOfRowsResult\r\n            // \r\n          " +
                    "  this.lbNumberOfRowsResult.AutoSize = true;\r\n            this.lbNumberOfRowsRes" +
                    "ult.Location = new System.Drawing.Point(0, 474);\r\n            this.lbNumberOfRow" +
                    "sResult.Name = \"lbNumberOfRowsResult\";\r\n            this.lbNumberOfRowsResult.Fo" +
                    "reColor = System.Drawing.Color.Red;\r\n            this.lbNumberOfRowsResult.Size " +
                    "= new System.Drawing.Size(39, 20);\r\n            this.lbNumberOfRowsResult.TabInd" +
                    "ex = 11;\r\n            this.lbNumberOfRowsResult.Text = \"# Number Of Rows\";\r\n    " +
                    "        // \r\n            // cbFilter\r\n            // \r\n            this.cbFilter" +
                    ".DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;\r\n            t" +
                    "his.cbFilter.FormattingEnabled = true;\r\n            this.cbFilter.Location = new" +
                    " System.Drawing.Point(99, 139);\r\n            this.cbFilter.Name = \"cbFilter\";\r\n " +
                    "           this.cbFilter.Size = new System.Drawing.Size(160, 30);\r\n            t" +
                    "his.cbFilter.TabIndex = 62;\r\n            this.cbFilter.SelectedIndexChanged += n" +
                    "ew System.EventHandler(this.cbFilter_SelectedIndexChanged);\r\n            // \r\n  " +
                    "          // btFind\r\n            // \r\n            this.btFind.BackColor = System" +
                    ".Drawing.Color.Silver;\r\n            this.btFind.FlatAppearance.BorderColor = Sys" +
                    "tem.Drawing.Color.Black;\r\n            this.btFind.FlatAppearance.BorderSize = 2;" +
                    "\r\n            this.btFind.FlatAppearance.MouseDownBackColor = System.Drawing.Col" +
                    "or.Silver;\r\n            this.btFind.FlatAppearance.MouseOverBackColor = System.D" +
                    "rawing.Color.Gray;\r\n            this.btFind.FlatStyle = System.Windows.Forms.Fla" +
                    "tStyle.Flat;\r\n            this.btFind.Font = new System.Drawing.Font(\"Microsoft " +
                    "Sans Serif\", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.P" +
                    "oint, ((byte)(0)));\r\n            this.btFind.Location = new System.Drawing.Point" +
                    "(431, 133);\r\n            this.btFind.Margin = new System.Windows.Forms.Padding(4" +
                    ", 3, 4, 3);\r\n            this.btFind.Name = \"btFind\";\r\n            this.btFind.S" +
                    "ize = new System.Drawing.Size(120, 40);\r\n            this.btFind.TabIndex = 20;\r" +
                    "\n            this.btFind.Text = \"Find\";\r\n            this.btFind.UseVisualStyleB" +
                    "ackColor = false;\r\n            this.btFind.Click += new System.EventHandler(this" +
                    ".btFind_Click);\r\n            // \r\n            // lbFilterBy\r\n            // \r\n  " +
                    "          this.lbFilterBy.AutoSize = true;\r\n            this.lbFilterBy.Location" +
                    " = new System.Drawing.Point(0, 143);\r\n            this.lbFilterBy.Name = \"lbFilt" +
                    "erBy\";\r\n            this.lbFilterBy.Size = new System.Drawing.Size(93, 20);\r\n   " +
                    "         this.lbFilterBy.TabIndex = 60;\r\n            this.lbFilterBy.Text = \"Fil" +
                    "ter By :\";\r\n            // \r\n            // mtxtbFilterValue\r\n            // \r\n " +
                    "           this.mtxtbFilterValue.AllowPromptAsInput = false;\r\n            this.m" +
                    "txtbFilterValue.Location = new System.Drawing.Point(265, 140);\r\n            this" +
                    ".mtxtbFilterValue.Mask = \"00000000\";\r\n            this.mtxtbFilterValue.Name = \"" +
                    "mtxtbFilterValue\";\r\n            this.mtxtbFilterValue.PromptChar = \' \';\r\n       " +
                    "     this.mtxtbFilterValue.Size = new System.Drawing.Size(160, 27);\r\n           " +
                    " this.mtxtbFilterValue.TabIndex = 0;\r\n");
            
            #line 208 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            // \r\n            // ");
            
            #line 210 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "fm" : "uctrl"));
            
            #line default
            #line hidden
            
            #line 210 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\r\n            // \r\n            this.AutoScaleDimensions = new System.Drawing.Size" +
                    "F(11F, 20F);\r\n            this.AutoScaleMode = System.Windows.Forms.AutoScaleMod" +
                    "e.Font;\r\n            ");
            
            #line 214 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "this.ClientSize = new System.Drawing.Size(1032, 498);" : "this.Size = new System.Drawing.Size(1050, 545);"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 215 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfControlNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("            this.Controls.Add(this.");
            
            #line 216 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfControlNames[i]));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 217 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 218 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput && IsForm) { 
            
            #line default
            #line hidden
            this.Write("            this.Controls.Add(this.btCancel);\r\n");
            
            #line 220 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 220 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("            this.Controls.Add(this.btSave);\r\n");
            
            #line 222 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 223 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("            this.Controls.Add(this.dgv");
            
            #line 224 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(@");
            this.Controls.Add(this.mtxtbFilterValue);
            this.Controls.Add(this.cbFilter);
            this.Controls.Add(this.btFind);
            this.Controls.Add(this.lbFilterBy);
            this.Controls.Add(this.lbNumberOfRowsResult);
");
            
            #line 230 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.Font = new System.Drawing.Font(\"Microsoft Sans Serif\", 10.2F, Sy" +
                    "stem.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));\r\n " +
                    "           this.Margin = new System.Windows.Forms.Padding(4);\r\n            this." +
                    "Name = \"");
            
            #line 233 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((IsForm) ? "fm" : "uctrl"));
            
            #line default
            #line hidden
            
            #line 233 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 234 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsForm) { 
            
            #line default
            #line hidden
            this.Write("            this.MaximizeBox = false;\r\n            this.StartPosition = System.Wi" +
                    "ndows.Forms.FormStartPosition.CenterScreen;\r\n            this.Text = \"");
            
            #line 237 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName.Replace("_", " ")));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 238 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 238 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("            this.Load += new System.EventHandler(this.fm");
            
            #line 239 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("_Load);\r\n");
            
            #line 240 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 241 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).End" +
                    "Init();\r\n");
            
            #line 243 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 244 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("            ((System.ComponentModel.ISupportInitialize)(this.dgv");
            
            #line 245 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(")).EndInit();\r\n");
            
            #line 246 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.ResumeLayout(false);\r\n");
            
            #line 248 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput || IsView) { 
            
            #line default
            #line hidden
            this.Write("            this.PerformLayout();\r\n");
            
            #line 250 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n\r\n        #endregion\r\n\r\n");
            
            #line 256 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfCreatedObjectsOfControls.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 257 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfCreatedObjectsOfControls[i]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 258 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 259 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.Button btSave;\r\n");
            
            #line 261 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 261 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput && IsForm) { 
            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.Button btCancel;\r\n");
            
            #line 263 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 263 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsInput) { 
            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.ErrorProvider errorProvider1;\r\n");
            
            #line 265 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 266 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (IsView) { 
            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.DataGridView dgv");
            
            #line 267 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(@";
        private System.Windows.Forms.Label lbNumberOfRowsResult;
        private System.Windows.Forms.ComboBox cbFilter;
        private System.Windows.Forms.Label lbFilterBy;
        private System.Windows.Forms.Button btFind;
        private System.Windows.Forms.MaskedTextBox mtxtbFilterValue;
");
            
            #line 273 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 for (short i = 0; i < ListOfColunmData.Count; i++) { 
            
            #line default
            #line hidden
            
            #line 274 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (ListOfColunmData[i].Type == "bit") { 
            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.DataGridViewCheckBoxColumn col");
            
            #line 275 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 276 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 277 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 if (ListOfColunmData[i].Type != "bit") { 
            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.DataGridViewTextBoxColumn col");
            
            #line 278 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ListOfColunmData[i].NameWithout_));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 279 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 280 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            
            #line 281 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 285 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateUiLayerDesigner.tt"


string GetInitializedProperties(enControls ControlName, string ColumnName, short Index, bool IsAllowNull, Point point, bool IsLabel = false)
{
    string ColumnNameWithSpace = ColumnName.Replace("_", " ");
    ColumnName = ColumnName.Replace("_", "");
    string Value = "";

    switch (ControlName)
    {
        case enControls.Label:
            if (!IsLabel)
                    {
                        Value =
                            $"//\n" +
                            $"\t\t\t// lb{ColumnName}Result\n" +
                            $"\t\t\t//\n" +
                            $"\t\t\tthis.lb{ColumnName}Result.AutoSize = true;\n" +
                            $"\t\t\tthis.lb{ColumnName}Result.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                            $"\t\t\tthis.lb{ColumnName}Result.Name = \"lb{ColumnName}Result\";\n" +
                            $"\t\t\tthis.lb{ColumnName}Result.Size = new System.Drawing.Size(116, 25);\n" +
                            $"\t\t\tthis.lb{ColumnName}Result.TabIndex = {Index};\n" +
                            $"\t\t\tthis.lb{ColumnName}Result.Text = \"???\";";
                    }
                    else
                    {
                        Value =
                            $"//\n" +
                            $"\t\t\t// lb{ColumnName}\n" +
                            $"\t\t\t//\n" +
                            $"\t\t\tthis.lb{ColumnName}.AutoSize = true;\n" +
                            $"\t\t\tthis.lb{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                            $"\t\t\tthis.lb{ColumnName}.Name = \"lb{ColumnName}\";\n" +
                            $"\t\t\tthis.lb{ColumnName}.Size = new System.Drawing.Size(116, 25);\n" +
                            $"\t\t\tthis.lb{ColumnName}.TabIndex = {Index};\n" +
                            $"\t\t\tthis.lb{ColumnName}.Text = \"{RemoveAnyDigitsInString(ColumnNameWithSpace)} :\";";
                    }
            break;
        case enControls.CheckBox:
            Value =
                $"//\n" +
                $"\t\t\t// chb{ColumnName}\n" +
                $"\t\t\t//\n" +
                $"\t\t\tthis.chb{ColumnName}.AutoSize = true;\n" +
                $"\t\t\tthis.chb{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                $"\t\t\tthis.chb{ColumnName}.Name = \"chb{ColumnName}\";\n" +
                $"\t\t\tthis.chb{ColumnName}.Size = new System.Drawing.Size(160, 30);\n" +
                $"\t\t\tthis.chb{ColumnName}.TabIndex = {Index};\n" +
                $"\t\t\tthis.chb{ColumnName}.Text = \"{ColumnNameWithSpace}\";\n" +
                $"\t\t\tthis.chb{ColumnName}.UseVisualStyleBackColor = true;";
            break;
        case enControls.TextBox:
            Value =
                $"//\n" +
                $"\t\t\t// txtb{ColumnName}\n" +
                $"\t\t\t//\n" +
                $"\t\t\tthis.txtb{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                $"\t\t\tthis.txtb{ColumnName}.Name = \"txtb{ColumnName}\";\n" +
                $"\t\t\tthis.txtb{ColumnName}.Size = new System.Drawing.Size(160, 27);\n" +
                $"\t\t\tthis.txtb{ColumnName}.TabIndex = {Index};";
                if (!IsAllowNull)
                        Value += $"\n\t\t\tthis.txtb{ColumnName}.Validating += new System.ComponentModel.CancelEventHandler(this.InputControls_Validating);";
            break;
        case enControls.MaskedTextBox:
            Value =
                $"//\n" +
                $"\t\t\t// mtxtb{ColumnName}\n" +
                $"\t\t\t//\n" +
                $"\t\t\tthis.mtxtb{ColumnName}.AllowPromptAsInput = false;\n" +
                $"\t\t\tthis.mtxtb{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                $"\t\t\tthis.mtxtb{ColumnName}.Name = \"mtxtb{ColumnName}\";\n" +
                $"\t\t\tthis.mtxtb{ColumnName}.PromptChar = ' ';\n" +
                $"\t\t\tthis.mtxtb{ColumnName}.Size = new System.Drawing.Size(160, 27);\n" +
                $"\t\t\tthis.mtxtb{ColumnName}.TabIndex = {Index};";
                if (!IsAllowNull)
                        Value += $"\n\t\t\tthis.mtxtb{ColumnName}.Validating += new System.ComponentModel.CancelEventHandler(this.InputControls_Validating);";
            break;
        case enControls.DateTimePicker:
            Value =
                $"//\n" +
                $"\t\t\t// dtp{ColumnName}\n" +
                $"\t\t\t//\n" +
                $"\t\t\tthis.dtp{ColumnName}.Format = System.Windows.Forms.DateTimePickerFormat.Short;\n" +
                $"\t\t\tthis.dtp{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                $"\t\t\tthis.dtp{ColumnName}.Name = \"dtp{ColumnName}\";\n" +
                $"\t\t\tthis.dtp{ColumnName}.Size = new System.Drawing.Size(145, 27);\n" +
                $"\t\t\tthis.dtp{ColumnName}.TabIndex = {Index};";
            break;
        case enControls.ComboBox:
            Value =
                $"//\n" +
                $"\t\t\t// cb{ColumnName}\n" +
                $"\t\t\t//\n" +
                $"\t\t\tthis.cb{ColumnName}.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;\n" +
                $"\t\t\tthis.cb{ColumnName}.FormattingEnabled = true;\n" +
                $"\t\t\tthis.cb{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                $"\t\t\tthis.cb{ColumnName}.Name = \"cb{ColumnName}\";\n" +
                $"\t\t\tthis.cb{ColumnName}.Size = new System.Drawing.Size(221, 28);\n" +
                $"\t\t\tthis.cb{ColumnName}.TabIndex = {Index};";
                if (!IsAllowNull)
                        Value += $"\n\t\t\tthis.cb{ColumnName}.Validating += new System.ComponentModel.CancelEventHandler(this.InputControls_Validating);";
            break;
        default:
            Value =
                $"//\n" +
                $"\t\t\t// lb{ColumnName}\n" +
                $"\t\t\t//\n" +
                $"\t\t\tthis.lb{ColumnName}.AutoSize = true;\n" +
                $"\t\t\tthis.lb{ColumnName}.Location = new System.Drawing.Point({point.X}, {point.Y});\n" +
                $"\t\t\tthis.lb{ColumnName}.Name = \"lb{ColumnName}\";\n" +
                $"\t\t\tthis.lb{ColumnName}.Size = new System.Drawing.Size(116, 25);\n" +
                $"\t\t\tthis.lb{ColumnName}.TabIndex = {Index};\n" +
                $"\t\t\tthis.lb{ColumnName}.Text = \"{ColumnNameWithSpace}\";";
            break;
    }

    return Value;
}

void CaseSameColumnNameAndSameControlNameHandle(string ColumnName)
{
    if (ListOfColunmData != null)
    {
        byte Count = (byte)ListOfColunmData.Count(x => x.Name == ColumnName);

        if (Count > 1)
        {
            short Index = (short)ListOfColunmData.FindLastIndex(x => x.Name == ColumnName);

            ListOfColunmData[Index].Name = ListOfColunmData[Index].Name + 2;
        }
    }
}

List<string> GetListOfInitializedProperties()
{
    List<string> ListOfInitializedProperties = new List<string>();

    enControls ControlName = enControls.None;

    Point LabelPoint = new Point(0, 10);
    Point ControlPoint = new Point(210, 10);

    for (short i = 0; i < ListOfColunmData.Count; i++)
    {
        if (ListOfColunmData[i].Generate)
        {
            Enum.TryParse(ListOfColunmData[i].ControlName, out ControlName);

            if (ControlName != enControls.CheckBox)
            {
                ListOfInitializedProperties.Add(GetInitializedProperties(enControls.Label, ListOfColunmData[i].Name, i, ListOfColunmData[i].IsNullable, LabelPoint, true));
                
                ListOfInitializedProperties.Add(GetInitializedProperties(ControlName, ListOfColunmData[i].Name, i, ListOfColunmData[i].IsNullable, ControlPoint));
            }
            else
            {
                ListOfInitializedProperties.Add(GetInitializedProperties(ControlName, ListOfColunmData[i].Name, i, ListOfColunmData[i].IsNullable, ControlPoint));
            }

            if (ControlPoint.Y >= 425)
            {
                ControlPoint.Y = 10;
                ControlPoint.X += 440;

                LabelPoint.Y = 10;
                LabelPoint.X += 440;
            }
            else
            {
                ControlPoint.Y += 35;
                LabelPoint.Y += 35;
            }
        }
    }

    return ListOfInitializedProperties;
}

public static string GetControlName(enControls ControlName, string ColumnName, bool IsLabel = false)
        {
            switch (ControlName)
            {
                case enControls.Label:
                    if (!IsLabel)
                    {
                        return $"lb{ColumnName}Result";
                    }
                    else
                    {
                        return $"lb{ColumnName}";
                    }
                case enControls.CheckBox:
                    return $"chb{ColumnName}";
                case enControls.TextBox:
                    return $"txtb{ColumnName}";
                case enControls.MaskedTextBox:
                    return $"mtxtb{ColumnName}";
                case enControls.DateTimePicker:
                    return $"dtp{ColumnName}";
                case enControls.ComboBox:
                    return $"cb{ColumnName}";
                default:
                    return $"lb{ColumnName}";
            }
        }

        List<string> GetListOfControlNames()
        {
            List<string> ListOfControlNames = new List<string>();

            enControls ControlName = enControls.None;

            for (short i = 0; i < ListOfColunmData.Count; i++)
            {
                if (ListOfColunmData[i].Generate)
                {
                    Enum.TryParse(ListOfColunmData[i].ControlName, out ControlName);

                    if (ControlName != enControls.CheckBox)
                    {
                        ListOfControlNames.Add(GetControlName(enControls.Label, ListOfColunmData[i].NameWithout_, true));
                    }

                    ListOfControlNames.Add(GetControlName(ControlName, ListOfColunmData[i].NameWithout_));
                }
            }

            return ListOfControlNames;
        }


string GetControlInitialized(enControls ControlName, string ColumnName, bool IsLabel = false)
{
     switch (ControlName)
     {
          case enControls.Label:
               if (!IsLabel)
               {
                   return $"this.lb{ColumnName}Result = new System.Windows.Forms.{enControls.Label.ToString()}();";
               }
               else
               {
                   return $"this.lb{ColumnName} = new System.Windows.Forms.{enControls.Label.ToString()}();";
               }
          case enControls.CheckBox:
              return $"this.chb{ColumnName} = new System.Windows.Forms.{enControls.CheckBox.ToString()}();";
          case enControls.TextBox:
              return $"this.txtb{ColumnName} = new System.Windows.Forms.{enControls.TextBox.ToString()}();";
          case enControls.MaskedTextBox:
              return $"this.mtxtb{ColumnName} = new System.Windows.Forms.{enControls.MaskedTextBox.ToString()}();";
          case enControls.DateTimePicker:
              return $"this.dtp{ColumnName} = new System.Windows.Forms.{enControls.DateTimePicker.ToString()}();";
          case enControls.ComboBox:
              return $"this.cb{ColumnName} = new System.Windows.Forms.{enControls.ComboBox.ToString()}();";
          default:
              return $"this.lb{ColumnName} = new System.Windows.Forms.{enControls.Label.ToString()}();";
     }
}

List<string> GetListOfInitializedControls()
{
     List<string> ListOfInitializedControls = new List<string>();

     enControls ControlName = enControls.None;

     for (short i = 0; i < ListOfColunmData.Count; i++)
     {
         if (ListOfColunmData[i].Generate)
         {
              CaseSameColumnNameAndSameControlNameHandle(ListOfColunmData[i].Name);
                
              Enum.TryParse(ListOfColunmData[i].ControlName, out ControlName);

              if (ControlName != enControls.CheckBox)
              {
                  ListOfInitializedControls.Add(GetControlInitialized(enControls.Label, ListOfColunmData[i].NameWithout_, true));
              }

              ListOfInitializedControls.Add(GetControlInitialized(ControlName, ListOfColunmData[i].NameWithout_));
         }
     }

     return ListOfInitializedControls;
}

string GetCreatedObjectsOfControl(enControls ControlName, string ColumnName, bool IsLabel = false)
{  
      switch (ControlName)
      {
           case enControls.Label:
               if (!IsLabel)
               {
                   return $"private System.Windows.Forms.{ControlName.ToString()} lb{ColumnName}Result;";
               }
               else
               {
                   return $"private System.Windows.Forms.{ControlName.ToString()} lb{ColumnName};";
               }
           case enControls.CheckBox:
               return $"private System.Windows.Forms.{ControlName.ToString()} chb{ColumnName};";
           case enControls.TextBox:
               return $"private System.Windows.Forms.{ControlName.ToString()} txtb{ColumnName};";
           case enControls.MaskedTextBox:
               return $"private System.Windows.Forms.{ControlName.ToString()} mtxtb{ColumnName};";
           case enControls.DateTimePicker:
               return $"private System.Windows.Forms.{ControlName.ToString()} dtp{ColumnName};";
           case enControls.ComboBox:
               return $"private System.Windows.Forms.{ControlName.ToString()} cb{ColumnName};";
           default:
               return $"private System.Windows.Forms.{ControlName.ToString()} lb{ColumnName};";
      }
}

 List<string> GetListOfCreatedObjectsOfControls()
{
     List<string> ListOfCreatedObjectsOfControls = new List<string>();

     enControls ControlName = enControls.None;

      for (short i = 0; i < ListOfColunmData.Count; i++)
      {
           if (ListOfColunmData[i].Generate)
           {
                Enum.TryParse(ListOfColunmData[i].ControlName, out ControlName);

                if (ControlName != enControls.CheckBox)
                {
                    ListOfCreatedObjectsOfControls.Add(GetCreatedObjectsOfControl(enControls.Label, ListOfColunmData[i].NameWithout_, true));
                }

                ListOfCreatedObjectsOfControls.Add(GetCreatedObjectsOfControl(ControlName, ListOfColunmData[i].NameWithout_));
           }
      }

      return ListOfCreatedObjectsOfControls;
}


string RemoveAnyDigitsInString(string Value)
{
    for (short i = 0; i < Value.Length; i++)
    {
        if (char.IsDigit(Value[i]))
        {
            Value = Value.Replace(Value[i].ToString(), "");
        }
    }
    
    return Value;
}


public string NameSpace { get; set; } = "";
public bool IsInput { get; set; }
public bool IsView { get; set; }

// لو هذا المتغير بيساوي false معناها ان هيتم انشاء user control
public bool IsForm { get; set; }

public string TableSingleName { get; set; } = "";

string _TableName = "";
public string TableName
{
    get
    {
        return _TableName;
    }
    set
    {
        _TableName = value;

        _TableName = _TableName.Replace("_", "");
    }
}

private List<string> ListOfInitializedControls = new List<string>();
private List<string> ListOfCreatedObjectsOfControls = new List<string>();
private List<string> ListOfInitializedProperties = new List<string>();
private List<string> ListOfControlNames = new List<string>();

private List<clsColumnDataUILayer> _ListOfColunmData { get; set; }
public List<clsColumnDataUILayer> ListOfColunmData 
{
     get
     {
          if (_ListOfColunmData == null)
          {
               return new List<clsColumnDataUILayer>();
          }
          else
          {
               return _ListOfColunmData;
          }
     }
     set
     {
          _ListOfColunmData = value;

          if (_ListOfColunmData != null)
          {
                ListOfInitializedControls = GetListOfInitializedControls();
                ListOfCreatedObjectsOfControls = GetListOfCreatedObjectsOfControls();
                ListOfInitializedProperties = GetListOfInitializedProperties();
                ListOfControlNames = GetListOfControlNames();
          }
     }
}



        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RuntimeTextTemplateUiLayerDesignerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
