// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator_BusinessLayer
{
    using System.Collections.Generic;
    using System.Linq;
    using CodeGenerator_Modules;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RuntimeTextTemplateDataAccessLayer : RuntimeTextTemplateDataAccessLayerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 5 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (!IsAppendMode) { 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;\r\n" +
                    "using Microsoft.Data.SqlClient;\r\nusing ");
            
            #line 10 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModulesLayerNameSpace));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 11 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 14 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (!IsAppendMode) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 15 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 17 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("Repository\r\n    {\r\n");
            
            #line 19 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            
            #line 20 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (IncludeAdd) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> AddAsync(cls");
            
            #line 21 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 23 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(" != null && ");
            
            #line 23 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(@".IsFull())
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);

                    string AddQuery = @""insert into [");
            
            #line 32 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("] (\r\n");
            
            #line 33 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 for (short i = 0; i < Columns.Count; i++) { 
                                if (Columns[i].IsPrimaryKey)
                                            continue;
            
            #line default
            #line hidden
            this.Write("                             [");
            
            #line 36 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Columns[i].Name));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 36 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < Columns.Count - 1) ? ", " : " )"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 37 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                            values (\r\n");
            
            #line 39 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 for (short i = 0; i < Columns.Count; i++) { 
                                    if (Columns[i].IsPrimaryKey)
                                            continue;
            
            #line default
            #line hidden
            this.Write("                             @");
            
            #line 42 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Columns[i].NameWithout_));
            
            #line default
            #line hidden
            
            #line 42 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < Columns.Count - 1) ? ", " : " );"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                             select Scope_Identity();\";\r\n\r\n                    Co" +
                    "mmand = new SqlCommand(AddQuery, Connection);\r\n\r\n");
            
            #line 48 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AddOrUpdateFunctionParamertersHandled(Columns)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n                    await Connection.OpenAsync();\r\n\r\n                    obje" +
                    "ct? Obj = await Command.ExecuteScalarAsync();\r\n\r\n                    if (Obj != " +
                    "null)\r\n                    {\r\n                        ");
            
            #line 56 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AddFunctionResultHandles()));
            
            #line default
            #line hidden
            this.Write(@"
                        return true;
                    }
                }
                catch (Exception ex)
                {
                    clsEventLog.WriteToEventLog(ex.Message, enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 81 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 83 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (IncludeUpdate) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> UpdateAsync(cls");
            
            #line 84 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 84 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 86 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
if (Columns.Find(x => x.Name == UpdateParameterName).Type == "string") { 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(" != null && !string.IsNullOrWhiteSpace(");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(") && ");
            
            #line 87 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(".IsFull(true))\r\n");
            
            #line 88 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            
            #line 89 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (Columns.Find(x => x.Name == UpdateParameterName).Type != "string") { 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(" != null && ");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleCorrectCheckParamerter(UpdateParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(" && ");
            
            #line 90 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(".IsFull(true))\r\n");
            
            #line 91 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);

                    string UpdateQuery = @""update [");
            
            #line 100 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("] set \r\n");
            
            #line 101 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 for (short i = 0; i < Columns.Count; i++) { 
                                if (Columns[i].IsPrimaryKey)
                                            continue;
            
            #line default
            #line hidden
            this.Write("                             [");
            
            #line 104 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Columns[i].Name));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 104 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Columns[i].NameWithout_));
            
            #line default
            #line hidden
            
            #line 104 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((i < Columns.Count - 1) ? ", " : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 105 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                             where [");
            
            #line 106 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateParameterName));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 106 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(";\";\r\n\r\n                    Command = new SqlCommand(UpdateQuery, Connection);\r\n\r\n" +
                    "                    Command.Parameters.AddWithValue(\"@");
            
            #line 110 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 110 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 110 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 112 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AddOrUpdateFunctionParamertersHandled(Columns)));
            
            #line default
            #line hidden
            this.Write(@"

                    await Connection.OpenAsync();

                    if (await Command.ExecuteNonQueryAsync() > 0)
                    {
                        return true;
                    }
                }
                catch (Exception ex)
                {
                    clsEventLog.WriteToEventLog(ex.Message, enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 142 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 144 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (IncludeFind) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<cls");
            
            #line 145 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("?> FindAsync(");
            
            #line 145 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleParameter(FindParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 147 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleCorrectCheckParamerter(FindParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@")
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;
                SqlDataReader? Reader = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);

                    string FindQuery = @""select * from [");
            
            #line 157 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("] where [");
            
            #line 157 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindParameterName));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 157 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(";\";\r\n\r\n                    Command = new SqlCommand(FindQuery, Connection);\r\n\r\n  " +
                    "                  Command.Parameters.AddWithValue(\"@");
            
            #line 161 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 161 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n                    await Connection.OpenAsync();\r\n\r\n                    Re" +
                    "ader = await Command.ExecuteReaderAsync();\r\n\r\n");
            
            #line 167 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindOrGetAllFunctionColumnOrdinalHandled(Columns)));
            
            #line default
            #line hidden
            this.Write("\r\n                    if (await Reader.ReadAsync())\r\n                    {\r\n     " +
                    "                   return new cls");
            
            #line 170 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("\r\n                        {\r\n");
            
            #line 172 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindOrGetAllFunctionParamertersHandled(Columns)));
            
            #line default
            #line hidden
            this.Write(@"
                        };
                    }
                }
                catch (Exception ex)
                {
                    clsEventLog.WriteToEventLog(ex.Message, enLogType.Error);
                }
                finally
                {
                    if (Reader != null)
                    {
                        Reader.Close();
                        Reader.Dispose();
                    }

                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return  null;
        }
");
            
            #line 203 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 205 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (IncludeGetAll) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<List<cls");
            
            #line 206 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(">?> GetAll");
            
            #line 206 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Async()\r\n        {\r\n            SqlConnection? Connection = null;\r\n            Sq" +
                    "lCommand? Command = null;\r\n            SqlDataReader? Reader = null;\r\n\r\n        " +
                    "    List<cls");
            
            #line 212 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(">? ListOf");
            
            #line 212 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n\r\n            try\r\n            {\r\n                Connection = new SqlC" +
                    "onnection(clsConnectionString.ConnectionString);\r\n\r\n                string GetAl" +
                    "lQuery = @\"select * from [");
            
            #line 218 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(@"];"";

                Command = new SqlCommand(GetAllQuery, Connection);

                await Connection.OpenAsync();

                Reader = await Command.ExecuteReaderAsync();

                if (Reader.HasRows)
                {
                    ListOf");
            
            #line 228 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" = new List<cls");
            
            #line 228 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n");
            
            #line 230 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindOrGetAllFunctionColumnOrdinalHandled(Columns)));
            
            #line default
            #line hidden
            this.Write("\r\n                    while (await Reader.ReadAsync())\r\n                    {\r\n  " +
                    "                      ListOf");
            
            #line 233 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Add(new cls");
            
            #line 233 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableSingleName));
            
            #line default
            #line hidden
            this.Write("\r\n                        {\r\n");
            
            #line 235 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FindOrGetAllFunctionParamertersHandled(Columns)));
            
            #line default
            #line hidden
            this.Write(@"
                        });
                    }
                }
            }
            catch (Exception ex)
            {
                clsEventLog.WriteToEventLog(ex.Message, enLogType.Error);
            }
            finally
            {
                if (Reader != null)
                {
                    Reader.Close();
                    Reader.Dispose();
                }

                if (Command != null)
                {
                    Command.Dispose();
                }

                if (Connection != null)
                {
                    Connection.Close();
                    Connection.Dispose();
                }
                
            }

            return ListOf");
            
            #line 265 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n");
            
            #line 267 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 269 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (IncludeDelete) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> DeleteAsync(");
            
            #line 270 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleParameter(DeleteParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 272 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleCorrectCheckParamerter(DeleteParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@")
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);

                    string DeleteQuery = ""delete from [");
            
            #line 281 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("] where [");
            
            #line 281 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DeleteParameterName));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 281 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(";\";\r\n\r\n                    Command = new SqlCommand(DeleteQuery, Connection);\r\n\r\n" +
                    "                    Command.Parameters.AddWithValue(\"@");
            
            #line 285 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 285 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DeleteParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@");

                    await Connection.OpenAsync();

                    return await Command.ExecuteNonQueryAsync() > 0;
                }
                catch (Exception ex)
                {
                    clsEventLog.WriteToEventLog(ex.Message, enLogType.Error);
                }
                finally
                {
                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 312 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 314 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (IncludeExist) { 
            
            #line default
            #line hidden
            this.Write("        public static async Task<bool> IsExistAsync(");
            
            #line 315 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleParameter(ExistParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 317 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleCorrectCheckParamerter(ExistParameterName).Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@")
            {
                SqlConnection? Connection = null;
                SqlCommand? Command = null;
                SqlDataReader? Reader = null;

                try
                {
                    Connection = new SqlConnection(clsConnectionString.ConnectionString);

                    string FindQuery = ""select [");
            
            #line 327 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExistParameterName));
            
            #line default
            #line hidden
            this.Write("] from [");
            
            #line 327 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("] where [");
            
            #line 327 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExistParameterName));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 327 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(";\";\r\n\r\n                    Command = new SqlCommand(FindQuery, Connection);\r\n\r\n  " +
                    "                  Command.Parameters.AddWithValue(\"@");
            
            #line 331 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 331 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExistParameterName.Replace("_", "")));
            
            #line default
            #line hidden
            this.Write(@");

                    await Connection.OpenAsync();

                    Reader = await Command.ExecuteReaderAsync();

                    if (Reader.HasRows)
                    {
                        return true;
                    }
                }
                catch (Exception ex)
                {
                    clsEventLog.WriteToEventLog(ex.Message, enLogType.Error);
                }
                finally
                {
                    if (Reader != null)
                    {
                        Reader.Close();
                        Reader.Dispose();
                    }

                    if (Command != null)
                    {
                        Command.Dispose();
                    }

                    if (Connection != null)
                    {
                        Connection.Close();
                        Connection.Dispose();
                    }
                }
            }

            return false;
        }
");
            
            #line 369 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        // Never delete this comment\r\n        // [EXTRA_METHODS_HERE]\r\n\r\n");
            
            #line 374 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 if (!IsAppendMode) { 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            
            #line 377 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 379 "D:\Visual Studio 2022 Projects\CodeGenerator_AppWindowsForms\CodeGenerator_BusinessLayer\RuntimeTextTemplateDataAccessLayer.tt"


public string TableName { get; set; } = "";
public string NamespaceName { get; set; } = "";
public List<clsColumnDataDataAccessLayer> Columns { get; set; }
public string ModulesLayerNameSpace { get; set; } = "";
public string TableSingleName { get; set; } = "";

public bool IncludeAdd { get; set; }
public bool IncludeUpdate { get; set; }
public bool IncludeFind { get; set; }
public bool IncludeExist { get; set; }
public bool IncludeGetAll { get; set; }
public bool IncludeDelete { get; set; }

public bool IsAppendMode { get; set; } = false;

private string _updateParameterName = "";
public string UpdateParameterName 
{ 
    get { return _updateParameterName; } 
    set
    {
        _updateParameterName = value;
        _updateParameterName = Columns.Find(x => x.Name == _updateParameterName) == null ? Columns[0].Name : _updateParameterName;
    }
}

private string _findParameterName = "";
public string FindParameterName 
{ 
    get { return _findParameterName; } 
    set
    {
        _findParameterName = value;
        _findParameterName = Columns.Find(x => x.Name == _findParameterName) == null ? Columns[0].Name : _findParameterName;
    }
}

private string _existParameterName = "";
public string ExistParameterName 
{ 
    get { return _existParameterName; } 
    set
    {
        _existParameterName = value;
        _existParameterName = Columns.Find(x => x.Name == _existParameterName) == null ? Columns[0].Name : _existParameterName;
    }
}

private string _deleteParameterName = "";
public string DeleteParameterName 
{ 
    get { return _deleteParameterName; }
    set
    {
        _deleteParameterName = value;
        _deleteParameterName = Columns.Find(x => x.Name == _deleteParameterName) == null ? Columns[0].Name : _deleteParameterName;
    }
}

private List<string> DataTypesWithoutString = new List<string> { "int", "double", "float", "short", "decimal", "long", "byte", "DateTime", "bool" };
private List<string> DataTypesWithoutStringAndDateTimeAndBoolan = new List<string> { "int", "double", "float", "short", "decimal", "long", "byte" };


public string HandleParameter(string ParameterName)
{
     clsColumnDataDataAccessLayer Col = Columns.Find(x => x.Name == ParameterName);

     if (Col != null)
     {
         return Col.Type + " " + ParameterName;
     }
     else
     {
         return "";
     }
}

public string HandleCorrectCheckParamerter(string ParameterName)
{
    clsColumnDataDataAccessLayer Col = Columns.Find(x => x.Name == ParameterName);
    
    if (Col != null)
    {
        if (DataTypesWithoutStringAndDateTimeAndBoolan.Contains(Col.Type))
        {
            return ParameterName + " > 0";
        }
        else if (Col.Type == "DateTime")
        {
            return ParameterName + " != default";
        }
        else
        {
            return "!string.IsNullOrWhiteSpace(" + ParameterName + ")";
        }
    }

    return "";
}

public string AddOrUpdateFunctionParamertersHandled(List<clsColumnDataDataAccessLayer> Columns)
{
    string Value = "";
    string Space = "\t\t\t\t\t";
    Value += Space;

    for (short i = 0; i < Columns.Count; i++)
    {
        if (Columns[i].IsPrimaryKey)
            continue;

        if (Columns[i].IsNullable && Columns[i].Type == "string")
        {
            Value += $"Command.Parameters.AddWithValue(\"@{Columns[i].NameWithout_}\", string.IsNullOrWhiteSpace({TableSingleName}.{Columns[i].NameWithout_}) ? DBNull.Value : {TableSingleName}.{Columns[i].NameWithout_});{GetCorrectEnd(i, Columns.Count, Space)}";
        }
        else if (Columns[i].IsNullable && Columns[i].Type != "string")
        {
            Value += $"Command.Parameters.AddWithValue(\"@{Columns[i].NameWithout_}\", {TableSingleName}.{Columns[i].NameWithout_} == null ? DBNull.Value : {TableSingleName}.{Columns[i].NameWithout_});{GetCorrectEnd(i, Columns.Count, Space)}";
        }
        else if (!Columns[i].IsNullable)
        {
            Value += $"Command.Parameters.AddWithValue(\"@{Columns[i].NameWithout_}\", {TableSingleName}.{Columns[i].NameWithout_});{GetCorrectEnd(i, Columns.Count, Space)}";
        }
    }

    return Value;
}

private string GetCorrectEnd(short i, int Count, string Space)
{
    return i + 1 == Count ? "" : $"\n{Space}";
}

public string FindOrGetAllFunctionColumnOrdinalHandled(List<clsColumnDataDataAccessLayer> Columns)
{
    string Value = "";
    string Space = "\t\t\t\t\t";
    Value += Space;

    for (short i = 0; i < Columns.Count; i++)
    {
        Value += $"byte {Columns[i].NameWithout_}Ordinal = (byte)Reader.GetOrdinal(\"{Columns[i].Name}\");\n{Space}";
    }

    return Value;
}

public string FindOrGetAllFunctionParamertersHandled(List<clsColumnDataDataAccessLayer> Columns)
{
    string Value = "";
    string Space = "\t\t\t\t\t\t\t";
    Value += Space;

    for (short i = 0; i < Columns.Count; i++)
    {
        if (Columns[i].IsNullable)
        {
            if (Columns[i].Type == "DateTime")
            {
                Value += $"{Columns[i].NameWithout_} = Reader.IsDBNull({Columns[i].NameWithout_}Ordinal) ? null : Reader.GetDateTime({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
            }
            else if (DataTypesWithoutString.Contains(Columns[i].Type))
            {
                Value += $"{Columns[i].NameWithout_} = Reader.IsDBNull({Columns[i].NameWithout_}Ordinal) ? null : ";
                
                if (Columns[i].Type == "int")
                {
                    Value += $"Reader.GetInt32({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "long")
                {
                    Value += $"Reader.GetInt64({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "bool")
                {
                    Value += $"Reader.GetBoolean({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "short")
                {
                    Value += $"Reader.GetInt16({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "float")
                {
                    Value += $"Reader.GetFloat({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "decimal")
                {
                    Value += $"Reader.GetDecimal({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "byte")
                {
                    Value += $"Reader.GetInt16({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "double")
                {
                    Value += $"Reader.GetDouble({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
            }
            else // if (Columns[i].Type = "string")
            {
                Value += $"{Columns[i].NameWithout_} = Reader.IsDBNull({Columns[i].NameWithout_}Ordinal) ? null : Reader.GetString({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
            }
        }
        else // (!Columns[i].IsNullable)
        {
            if (Columns[i].Type == "DateTime")
            {
                Value += $"{Columns[i].NameWithout_} = Reader.GetDateTime({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
            }
            else if (DataTypesWithoutString.Contains(Columns[i].Type))
            {                
                if (Columns[i].Type == "int")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetInt32({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "long")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetInt64({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "bool")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetBoolean({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "short")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetInt16({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "float")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetFloat({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "decimal")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetDecimal({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "byte")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetInt16({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
                else if (Columns[i].Type == "double")
                {
                    Value += $"{Columns[i].NameWithout_} = Reader.GetDouble({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
                }
            }
            else // if (Columns[i].Type = "string")
            {
                Value += $"{Columns[i].NameWithout_} = Reader.GetString({Columns[i].NameWithout_}Ordinal){GetCorrectEndFindOrGetAllFunction(i, Columns.Count, Space)}";
            }
        }
    }

    return Value;
}

private string GetCorrectEndFindOrGetAllFunction(short i, int Count, string Space)
{
    return i + 1 == Count ? "" : $",\n{Space}";
}

private string AddFunctionResultHandles()
{
    string Value = "";
    
    for (short i = 0; i < Columns.Count; i++) 
    { 
        if (Columns[i].IsPrimaryKey)
        { 
             Value += $"{TableSingleName}.{Columns[i].NameWithout_} = int.Parse(Obj.ToString() ?? \"0\");";
             break;
        }
    }

    if (string.IsNullOrWhiteSpace(Value)) 
    { 
        if (Columns[0].Type == "DateTime") 
        {
             Value += $"{TableSingleName}.{Columns[0].NameWithout_} = {Columns[0].Type}.Parse(Obj.ToString() ?? \"0001-1-1\");";
        }
        else if (Columns[0].Type == "string") { 
             Value += $"{TableSingleName}.{Columns[0].NameWithout_} = Obj as string ?? \"\";";
        } 
        else // (Columns[0].Type != "DateTime" && Columns[0].Type != "string") 
        {
             Value += $"{TableSingleName}.{Columns[0].NameWithout_} = {Columns[0].Type}.Parse(Obj.ToString() ?? \"0\");";
        }
    }

    return Value;
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RuntimeTextTemplateDataAccessLayerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
